### ISSUE TITLE
How to solve the problem of illegal characters in the new snmp.yml?

### ISSUE THREAD

**Issue by aliuzzz** [prometheus/snmp_exporter#967] opened 2023-08-24 01:40 UTC
When I was testing, I found the following issues：
“error collecting metric Desc{fqName: "snmp_error", help: "Error calling NewConstMetric", constLabels: {}, variableLabels: []}: error for metric ifAdminStatus with labels [526 for_old95��_7506 Ten-GigabitEthernet5/0/41 Ten-GigabitEthernet5/0/41] from indexOids [526]: label value "for_old95\xa1\xaa_7506" is not valid UTF-8”

Can I only add relabel in prometheus.yml for this issue_ Configure to solve it? Can relevant fields be directly added to snmp.yml to solve the problem?

**Comment by SuperQ** [comment] 2023-08-24 07:02
This doesn't appear to have to do with the snmp.yml, but your device is returning invalid data.

**Comment by SuperQ** [comment] 2023-08-24 07:04
Duplicate of https://github.com/prometheus/snmp_exporter/issues/637

**Closed by SuperQ** 2023-08-24 07:04 UTC
