### ISSUE TITLE
Consider publishing generator image on dockerhub

### ISSUE THREAD

**Issue by adam-dej** [prometheus/snmp_exporter#368] opened 2018-12-21 11:43 UTC
It would be helpful if users could run config generator just by pulling a docker image. However, I only found https://hub.docker.com/r/aabbate/secg/ on Dockerhub, and it does not contain the latest version right now.

This repo already has a working Dockerfile for the generator, would it be possible to publish the resulting image as part of the automated build process?

**Comment by SuperQ** [comment] 2018-12-21 12:11
Sure, we could add this to our build. Have you looked at our CircleCI config? Care to try adding it? 😁

**Comment by brian-brazil** [comment] 2018-12-21 12:51
Dupe of #223

**Closed by brian-brazil** 2018-12-21 12:51 UTC
