### ISSUE TITLE
Allow auth config to be kept in an independent config file (or maybe even add conf.d subfolder support)

### ISSUE THREAD

**Issue by frittentheke** [prometheus/snmp_exporter#912] opened 2023-07-10 11:39 UTC
### What did you expect to see?
With the recent (very much appreciated change) to split of auth and modules config (https://github.com/prometheus/snmp_exporter/pull/859), I would like to propose adding support for splitting them between two different files.
Since modules are usually auto-generated / rendered into `snmp.yml`, but the auth section is likely something configured manually or statically, having two files would make this a easier to handle in automation / config-management.

Another approach could be to support the `conf.d` pattern and allow for all of the config to be distributed in multiple config files. Something like Prometheus did for scrape configs (https://github.com/prometheus/prometheus/issues/8543). This would then allow to also place configs for individual modules into separate files.

**Comment by SuperQ** [comment] 2023-07-10 11:43
Duplicate of https://github.com/prometheus/snmp_exporter/issues/628

**Closed** 2023-07-10 11:43 UTC
Labels: duplicate
