### ISSUE TITLE
Add MIB override/tweaks to the generator

### ISSUE THREAD

**Issue by SuperQ** [prometheus/snmp_exporter#166] opened 2017-05-30 12:11 UTC
In order to support various MIB ~~bugs~~features we should have a series of overrides.

```yml
modules:
  example:
    walk: [sysUpTime, interfaces, ifXTable, etc]
    lookups:
      - old_index: ifIndex
        new_index: ifDescr
    string_regexps:
      - oid: stringPiOID
        regex: Pi is (\d+\.\d+)
    excludes:
      - uselessOID
      - otherUselessOID
```

TODO: configurations for `augments` and `syntax` changes.

Comments/suggestions welcome.

**Comment by SuperQ** [comment] 2017-05-30 12:12
CC: @RichiH @fjaeckel

**Comment by brian-brazil** [comment] 2017-05-30 12:13
Dupe of #150

**Closed by brian-brazil** 2017-05-30 12:13 UTC
