### ISSUE TITLE
Invalid label value - Error while scrapping data from targets

### ISSUE THREAD

**Issue by mohanprasaths** [prometheus/snmp_exporter#117] opened 2017-02-01 19:23 UTC
![selection_003](https://cloud.githubusercontent.com/assets/12637959/22522259/f5b4e234-e8e0-11e6-9b1b-79ff89537413.png)

Error - "**invalid label value "\xac\x1f\x0e\x83**""  - Error in prometheus
(**ac 1f 0e 83** - is the hex value of IP address)

This is how the data is polled in  SNMP Exporter - "**cipSecTunLocalAddr="¬ƒ**"
Is there any way to handle hex value ? If there is any other alternative way , please let me know.
Thanks in advance

**Comment by brian-brazil** [comment] 2017-02-01 19:38
Dupe of 116

**Closed** 2017-02-01 23:17 UTC
