### ISSUE TITLE
Unbale to generate SNMP.yml after latest update

### ISSUE THREAD

**Issue by tkdebnath** [prometheus/snmp_exporter#909] opened 2023-07-05 14:35 UTC
I am unable to generate the SNMP.yml file after the latest update. 

If Version 3 is set I am getting error while generating 

![image](https://github.com/prometheus/snmp_exporter/assets/16004445/10ecab4c-40a0-4879-848e-c5fefb1f1679)

And if Version 2 is set the generated SNMP.yml looks like this with "community"

![image](https://github.com/prometheus/snmp_exporter/assets/16004445/acd7f748-7711-41ce-9675-17c3fa02e280)

and getting error in snmp exporter docker

ts=2023-07-05T14:33:29.769Z caller=main.go:157 level=info msg="Starting snmp_exporter" version="(version=0.22.0, branch=HEAD, revision=7b0657fd99862a47f2f9f780f08a794ca7040ae7)"
ts=2023-07-05T14:33:29.769Z caller=main.go:158 level=info build_context="(go=go1.20.5, platform=linux/amd64, user=root@cfac3556bd96, date=20230615-13:29:47, tags=netgo)"
ts=2023-07-05T14:33:29.773Z caller=main.go:166 level=error msg="Error parsing config file" err="yaml: unmarshal errors:\n  line 3: field auth_name not found in type config.plain\n  line 13: field if_mib not found in type config.plain\n  line 945: cannot unmarshal !!int `2` into config.plain"

![image](https://github.com/prometheus/snmp_exporter/assets/16004445/a7df3a49-ad09-4458-a999-8e599f3ef2ee)

**Comment by SuperQ** [comment] 2023-07-05 15:15
The `version` refers to the config format version.

Duplicate of https://github.com/prometheus/snmp_exporter/issues/905

**Closed as completed by SuperQ** 2023-07-05 15:15 UTC
