### ISSUE TITLE
server returned HTTP status 400 Bad Request

### ISSUE THREAD

**Issue by Nurlan199206** [prometheus/snmp_exporter#314] opened 2018-07-11 06:19 UTC
Hi everyone.

im trying to get traffic bandwidth from Cisco router interface, but error 400.

someone know how to fix that? 

my `snmp.yml`
```
cisco_custom:
  version: 2
  auth:
    community: 12345
  walk:
  - 1.3.6.1.2.1.2.2.1.10.33
  - 1.3.6.1.2.1.2.2.1.10.33
  metrics:
  - name: snmp_IfinOctets.32
    oid: 1.3.6.1.2.1.2.2.1.10.33
    type: gauge
```
prometheus.yml
```
  - job_name: snmp
    static_configs:
      - targets:
        - 172.27.22.254  # SNMP device.
    metrics_path: /snmp
    params:
#      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.27.1.54:9116
```

![snmp](https://user-images.githubusercontent.com/22808731/42553843-57229776-8504-11e8-9b48-fd839d72313b.PNG)

**Comment by SuperQ** [comment] 2018-07-11 06:40
Is there anything in the log output of the snmp_exporter?

**Comment by brian-brazil** [comment] 2018-07-11 06:44
There's a duplicate entry in your walk.

**Comment by SuperQ** [comment] 2018-07-11 06:47
Also, I think the `.` in the metric name is invalid.

**Comment by Nurlan199206** [comment] 2018-07-11 07:51
i'm trying to turn on logging.

```
# /home/nurlan/snmp_exporter/snmp_exporter --log.level="debug"
INFO[0000] Starting snmp exporter (version=0.11.0, branch=HEAD, revision=e4591716c29459cb2a12b1bed129af519ad91d23)  source="main.go:138"
INFO[0000] Build context (go=go1.10.2, user=root@80735d30559d, date=20180530-10:24:52)  source="main.go:139"
INFO[0000] Listening on :9116                            source="main.go:218"
FATA[0000] listen tcp :9116: bind: address already in use  source="main.go:219"
```

**Comment by brian-brazil** [comment] 2018-07-11 08:08
You should use the generator to produce config files: https://github.com/prometheus/snmp_exporter/tree/master/generator

**Comment by Nurlan199206** [comment] 2018-07-11 08:09
@brian-brazil it's can be because of this?

![snmp2](https://user-images.githubusercontent.com/22808731/42558714-f71f7956-8513-11e8-99aa-b9e9f8da9264.PNG)

**Comment by RichiH** [comment] 2018-07-12 07:18
@Nurlan199206 You are calling the default module (translates to if_mib), but you should use cisco_custom instead.

As this is a user support question not a bug, I am closing this issue for now; if you have any more questions regarding this, please head over to https://groups.google.com/forum/#!forum/prometheus-users :)

**Closed by RichiH** 2018-07-12 07:18 UTC

**Comment by RichiH** [comment] 2018-07-12 07:35
@Nurlan199206 I opened https://github.com/prometheus/snmp_exporter/issues/317 to improve UX in such a case.

**Comment by Nurlan199206** [comment] 2018-07-12 11:15
guys i'm finally setup snmp with router, now i need graph values in MBits, like in Zabbix.

someone pls can put here properly query? help please. :)

my query: `rate(IfinOctets{instance="172.27.22.254",job="snmp"}[1m]) / 8`

![zabb1](https://user-images.githubusercontent.com/22808731/42629916-d4fdd9ce-85f6-11e8-92d5-b1ac2e551987.PNG)

![grafan1](https://user-images.githubusercontent.com/22808731/42629966-08bf7164-85f7-11e8-824b-357aa3c68df4.PNG)

**Comment by RichiH** [comment] 2018-07-12 12:23
If you are asking why the graphs do not look exactly the same, it's due to the different ways Zabbix and Prometheus calculate with the underlying data. Classic systems look a lot more static in their graphs, but that is not necessarily the actual truth.

But again, please move these questions to the https://groups.google.com/forum/#!forum/prometheus-users mailing list.
